apiVersion: v1
kind: ConfigMap
metadata:
  name: cavecanary-config-v${CAVECANARY_CONFIG_VERSION}
  namespace: default
data:
  config.cfg: |
    import os
    import json
    import logging
    # Statement for enabling the development environment
    INFOSERVICE_ENDPOINT = "https://${INFO_URL}"
    CLIENT_DATASTACK_NAME = "${DATASTACK_NAME}"
    SLACK_API_TOKEN = "${SLACK_API_TOKEN}"
    SLACK_CHANNEL = "${SLACK_CHANNEL}"
    NUM_TEST_ANNOTATIONS = ${NUM_TEST_ANNOTATIONS}
    CHECK_INTERVAL = ${CHECK_INTERVAL}
    LOGGING_FORMAT = '%(asctime)s - %(levelname)s - %(message)s'
    LOGGING_LOCATION = '/var/log/cavecanary/cavecanary.log'
    LOGGING_LEVEL = logging.ERROR

---
apiVersion: v1
kind: Service
metadata:
  name: cavecanary-service
spec:
  type: NodePort
  selector:
    app: cavecanary
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cavecanary
spec:
  selector:
    matchLabels:
      app: cavecanary
  template:
    metadata:
      labels:
        app: cavecanary
    spec:
      tolerations:
        - key: "pool"
          operator: "Equal"
          value: "${LIGHTWEIGHT_POOL}"
          effect: "NoSchedule"
      nodeSelector:
        cloud.google.com/gke-nodepool: ${LIGHTWEIGHT_POOL}
      volumes:
        - name: cavecanary-config-volume
          configMap:
            name: cavecanary-config-v${CAVECANARY_CONFIG_VERSION}
      containers:
        - name: cavecanary
          image: ${DOCKER_REPOSITORY}/cavecanary:v${CAVECANARY_VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: cavecanary-config-volume
              mountPath: /app/cavecanary/config/
          env:
            - name: CAVECANARY_CONFIG_FILE
              value: /app/cavecanary/config/config.cfg
          resources:
            requests:
              memory: 1000Mi
              cpu: 200m
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 60
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 60
