steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker login --username=$$USERNAME --password=$$PASSWORD"]
    secretEnv: ["USERNAME", "PASSWORD"]
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker build -t gcr.io/$PROJECT_ID/CAVEcanary:$TAG_NAME .
    timeout: 600s
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker tag gcr.io/$PROJECT_ID/CAVEcanary:$TAG_NAME $$USERNAME/materializationengine:$TAG_NAME",
      ]
    secretEnv: ["USERNAME"]
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker push $$USERNAME/CAVEcanary:$TAG_NAME"]
    secretEnv: ["USERNAME"]
images:
  - "gcr.io/$PROJECT_ID/CAVEcanary:$TAG_NAME"
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/docker-password/versions/1
      env: "PASSWORD"
    - versionName: projects/$PROJECT_ID/secrets/docker-username/versions/1
      env: "USERNAME"
